services:
   postgresdb:
      container_name: postgresdb
      image: postgres:16.0
      volumes:
         - ./data/postgres:/var/lib/postgresql/data
      ports:
         - 0.0.0.0:${PGDB_PORT}:5432
      environment:
         POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
         POSTGRES_USER: ${DB_USER}
         POSTGRES_DB: ${DB_NAME}
         PGDATA: /var/lib/postgresql/data/pgdata
      networks:
         - sae

   web:
      container_name: web
      image: apache-pdo:1.0
      build: .
      volumes:
         - ./data/html:/var/www/html
         - ./data/include:/var/www/include
         - ./data/cfg/php.ini:/usr/local/etc/php/php.ini
      environment:
         VIRTUAL_HOST: ${EQUIPE}.ventsdouest.dev
         LETSENCRYPT_HOST: ${EQUIPE}.ventsdouest.dev
         LETSENCRYPT_EMAIL: gildas@bigpapoo.com
      env_file: ".env"
      networks:
         - sae 
         - webproxy_back
      ports:
         - '8080:80'
      depends_at:
         - postgresdb
      user: root

   pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
         VIRTUAL_HOST: dbadmin-${EQUIPE}.ventsdouest.dev
         LETSENCRYPT_HOST: dbadmin-${EQUIPE}.ventsdouest.dev
         LETSENCRYPT_EMAIL: gildas@bigpapoo.com
         PGADMIN_DEFAULT_EMAIL: ${EQUIPE}@dbadmin-sae.com
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
         PGADMIN_DISABLE_POSTFIX: true
      networks:
         - sae
         - webproxy_back
      depends_at:
         - postgresdb

networks:
   sae:
   webproxy_back:
      external: true
