name: Reset database
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Reset Database.yml'
      - '**.sql'
jobs:
  reset_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Reset database
        run: 'cd "$GITHUB_WORKSPACE"/script && ./server-run-script.bash ./server/reset-database.bash'