name: Reset Database
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.sql'
jobs:
  reset_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Reset Database
        run: |
          env
          set -xeu
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          ssh debian@${{ secrets.ARTIFACT_HOST }} << 'EOF'
              set -xeu
              cd /docker/sae/data
              sudo git pull
              cd sql
              for f in *.sql; do
                sudo docker cp "$f" postgresdb:/"$f"
              done
              sudo docker exec -w / postgresdb bash -c '
                set -xeu
                for f in /creaBDD.sql /vuesBDD.sql /fonctions_triggers.sql /data-depts-communes.sql /data.sql
                  do echo run "$f"
                  psql -U sae -d postgres -f "$f"
                done
              '
              bash ../base_imgs/copy.bash

          EOF