name: Reset Database
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.sql'
      - '**/reset_db.yml'
jobs:
  reset_db:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Database
        run: |
          set -xeu
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          ssh debian@${{ secrets.ARTIFACT_HOST }} << 'EOF'
              set -xeu
              cd /docker/sae/data
              sudo git pull
              cd sql
              shopt -s globstar
              for f in **/*.sql; do
                sudo docker cp "$f" postgresdb:/"$f"
              done
              sudo docker exec -w / postgresdb bash -c '
                set -xeu
                for f in /creaBDD.sql /fonctions.sql /vuesBDD.sql /triggers.util.sql /triggers.sql /bigdata.sql /data.sql /images.sql /offre/*.sql
                  do echo run "$f"
                  mkdir -p "$(dirname "$f")"
                  psql -v ON_ERROR_STOP=on -U sae -d postgres -f "$f"
                done
              '
          EOF