name: Reset Database Notify Discord
on:
  workflow_run:
    workflows: [Reset Database]
    types:
      - completed
defaults:
  run:
    shell: bash
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Send Discord notification
        env:
          ACTOR: "[${{ github.event.workflow_run.actor.login }}](${{ github.event.workflow_run.actor.html_url }})"
          CONCLUSION: "${{ github.event.workflow_run.conclusion }}"
          DISCORD_WEBHOOK_URL: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          HTML_URL: "${{ github.event.workflow_run.html_url }}"
          REPOSITORY: "${{ github.repository }}"
          RUN_ID: "${{ github.event.workflow_run.id }}"
          TIMESTAMP: "${{ github.event.workflow_run.updated_at }}"
          WORKFLOW_ID: "${{ github.event.workflow_run.id }}"
        run: '$GITHUB_WORKSPACE/script/Reset Database Notify Discord.bash'

