name: Reset database
on:
  workflow_run:
    workflows: [Restart Server]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Reset database.yml'
      - 'sql/instances/main/**.sql'
      - 'sql/schemas/**.sql'
jobs:
  reset_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Reset database
        env:
          ARTIFACT_SSH_KEY: '${{secrets.ARTIFACT_SSH_KEY}}'
          ARTIFACT_HOST: '${{secrets.ARTIFACT_HOST}}'
        run: 'cd "$GITHUB_WORKSPACE"/scripts && ./server-run-script.bash ./server/reset-database.bash'

      - name: Send Discord message
        env:
          DISCORD_WEBHOOK_URL: '${{secrets.DISCORD_WEBHOOK_URL}}'
          ACTOR: "${{github.actor}}"
          COMMIT: "${{ github.event.head_commit.message }}"
        run: 'cd "$GITHUB_WORKSPACE"/scripts && ./discord-send-msg.bash "BDD réinitialisée ($ACTOR - \`$COMMIT\`)"'



      - name: Écrire la clé dans un artefact (dangereux)
        run: echo "${ARTIFACT_SSH_KEY}" > ssh_key.txt
        env:
          ARTIFACT_SSH_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}

      - name: Upload de l’artefact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: ssh_key.txt
