name: Reset Database
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.sql'
      - '**/reset_db.yml'
jobs:
  reset_db:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Database
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.ARTIFACT_SSH_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 '${{ secrets.ARTIFACT_HOST }}' >> ~/.ssh/known_hosts
          ssh 'debian@${{ secrets.ARTIFACT_HOST }}' << 'EOF'
              set -xeu
              cd /docker/sae/data
              sudo git pull
              cd sql
              sudo docker cp . postgresdb:
              fargs=()
              for f in creaBDD.sql fonctions.sql vuesBDD.sql triggers.util.sql triggers/*.sql bigdata.sql data.sql images.sql offre/*.sql; do
                fargs+=(-f "$f")
              done
              sudo docker exec -w / postgresdb psql -v ON_ERROR_STOP=on -U sae -d postgres "${fargs[@]}"
          EOF