name: 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Restart Server.yml'
defaults:
  run:
    shell: bash
jobs:
  restart_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Restart Server
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.ARTIFACT_SSH_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 '${{ secrets.ARTIFACT_HOST }}' >> ~/.ssh/known_hosts
          ssh 'debian@${{ secrets.ARTIFACT_HOST }}' bash < "$GITHUB_WORKSPACE/script/Restart Server.bash"
