name: Restart Server
on: workflow_dispatch
jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Server
        run: |
          env
          set -xeu
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          ssh debian@${{ secrets.ARTIFACT_HOST }} << 'EOF'
              set -xeu
              docker compose down
              docker compose up -d
          EOF
