name: Update Server
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.sql'
jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
      - name: Update Server
        run: |
          set -xeu
          mkdir -p ~/.ssh
          echo '${{ secrets.ARTIFACT_SSH_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 '${{ secrets.ARTIFACT_HOST }}' >> ~/.ssh/known_hosts
          ssh 'debian@${{ secrets.ARTIFACT_HOST }}' << 'EOF'
              set -xeu
              cd /docker/sae/data
              sudo git pull
          EOF
