name: Update Server
on:
  push:
    branches:
      - main
jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Server
        run: |
          env
          mkdir ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          ssh debian@${{ secrets.ARTIFACT_HOST }} << EOF
              cd /docker/sae
              cd data
              sudo git pull
              cd ..
              sudo docker compose down
              sudo docker compose up -d
          EOF