name: Update Tchattator
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.c'
      - '**.h'
jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Update Tchattator
        env:
          ARTIFACT_SSH_KEY: '${{secrets.ARTIFACT_SSH_KEY}}'
          ARTIFACT_HOST: '${{secrets.ARTIFACT_HOST}}'
        run: 'cd "$GITHUB_WORKSPACE"/script && ./server-run-script.bash ./tchattator/update-tchattator.bash'

      - name: Send Discord message
        env:
          DISCORD_WEBHOOK_URL: '${{secrets.DISCORD_WEBHOOK_URL}}'
          ACTOR: "${{github.actor}}"
          COMMIT: "${{ github.event.head_commit.message }}"
          URL: "${{ github.event.head_commit.url }}"
        run: 'cd "$GITHUB_WORKSPACE"/script && ./discord-send-msg.bash "Tchattator mis à jour ($ACTOR - \`$COMMIT\`) ([github]($URL))"'
